apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: hermes-guestbook
spec:
  promotionFlows:
    - name: to-prod
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - '*deploy*'
    - name: demo
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - '*[demo]'
  promotionTemplate:
    versionSource:
      file: Chart.yaml
      jsonPath: $.appVersion
    promotion:
      values.yaml:
        jsonPaths:
          - $.image.tag
      Chart.yaml:
        jsonPaths:
          - $.appVersion
