apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: test
spec:
  promotionFlows:
    - namse: promotion-poc
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - '[promote]*'
  promotionTemplateRef: gitops-platform
