apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-gitops-runtime
  labels:
    codefresh.io/entity: runtime
    codefresh.io/internal: 'true'
spec:
  project: default
  source:
    repoURL: https://github.com/oleksandr-codefresh/cf-hermes-team_isc.git
    targetRevision: HEAD
    path: resources/hermes/chart
    helm:
      releaseName: cf-gitops-runtime
  destination:
    namespace: hermes
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: false
