gitops-runtime:
  app-proxy:
    replicaCount: 1
    config:
#      cors: http://local.codefresh.io
      argoCdUrl: http://argo-cd-server:80/argocd
    # image:
    #   tag: 1.2651.0-CR-22513-previous-logs-f9d05aa
  argo-workflows:
    controller:
      podGCDeleteDelayDuration: '300s'
      # replicas: 1
  argo-cd:
    global:
    # image:
    #   repository: xeonalex/personal-argocd-dev
    #   tag: 2.11-merge-3
    configs:
      params:
        server.basehref: /argocd
        server.rootpath: /argocd
        # controller.repo.server.timeout.seconds: "300"
      cm:
        codefresh.reporterVersion: v2
    eventReporter:
#      image:
#        repository: xeonalex/personal-argocd-dev
#        tag: 2.11-refactor-0
      enabled: "true"
      version: v2
      replicas: 1
      # env:
      #   - name: USE_GRPC
      #     value: "true"
    repoServer:
      # image:
      #   repository: docker.io/pashacodefresh/argocd
      #   tag: latest
      replicas: 1
    controller:
      # image:
      #   repository: docker.io/pashacodefresh/argocd
      #   tag: latest
      replicas: 1
    server:
      # image:
      #   repository: docker.io/pashacodefresh/argocd
      #   tag: latest
      replicas: 1
        # config:
        #   server.repo.server.timeout.seconds: 600s
        #   controller.repo.server.timeout.seconds: 600s
        # image:
        #   repository: docker.io/xeonalex/personal-argocd-dev
        #   tag: vuln-fix
        # service:
      # annotations:
      #   kubernetes.io/ingress.class: nginx-public
      # type: LoadBalancer - краще юзати ingress
  event-reporters:
    events:
      argoCDServerServicePort: 80/argocd
      # workflow:
      # eventSource:
      #   replicas: 0
      # sensor:
      #   replicas: 0
  gitops-operator:
    # image:
    #   repository: quay.io/codefresh/codefresh-gitops-operator
    #   tag: cr-24411-vuln-fixes
    env:
      ARGO_CD_URL: argo-cd-server:80/argocd
  global:
    # image:
    #   repository: docker.io/xeonalex/personal-argocd-dev
    #   tag: git-client
    codefresh:
      accountId: 669622463f08406c4055afcb
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
      # tls:
      #   # --  Custom CA certificates bundle for platform access with ssl
      #   caCerts:
      #     # -- Reference to existing secret
      #     secretKeyRef:
      #       name: test-cf-cert
      #       key: sa
    runtime:
      ingress:
        className: nginx-public
        enabled: true
        hosts:
          - hermes-team-prod.rnd.sandbox.codefresh.io
        protocol: https
      name: hermes
      isConfigurationRuntime: true
  installer:
    skipValidation: true
