apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vitalii-gitsource2
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cf-git-sources
  sources:
    - repoURL: https://github.com/vitalii-codefresh/vitalii-gitsource2.git
      path: .
      targetRevision: main
      directory:
        include: '*'
        exclude: ''
        recurse: true
  destination:
    namespace: vitalii-gitops-runtime
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
