apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hosted-apps
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: git-sources
  sources:
    - repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps.git
      path: hosted-apps
      targetRevision: hermes-prod-git-sources
      directory:
        include: '*'
        exclude: ''
        recurse: true
  destination:
    namespace: codefresh-hosted
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
