apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vitalii-test-source
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: git-sources
  sources:
    - repoURL: https://github.com/vitalii-codefresh/simple-server.git
      path: gitops/single-service
      targetRevision: develop
      directory:
        include: '*'
        exclude: ''
        recurse: true
  destination:
    namespace: codefresh-hosted
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
